### ISSUE TITLE
Bypassing error 429?

### ISSUE THREAD

**Issue by ewvikienkr** [un-ts/deeplx#6]
I tried sending a few requests to https://deeplx.vercel.app/translate but quickly got the "HTTPError: 429 Client Error: Too many requests". Is it correct to conclude that you are unable to consistently bypass this error either (I'm coming from https://github.com/ptrstn/deepl-translate/issues/16)? I saw you implemented the "method:" / "method :" fix already...

**Comment by lindeer** [comment]
same error, still reproduce, any idea? @ewvikienkr

**Comment by JounQin** [comment]
Sorry I didn't notice this issue previously, but I cannot reproduce it consistently, maybe the official API changed a bit, it may need some more reverse engineering but we lost the original referenced article.

**Comment by JounQin** [comment]
You cannot requests too much at a moment, that's why have to sleep on each test.

https://github.com/un-ts/deeplx/blob/f35e9d45234d9febf3546d4731e67a02829cf027/test/translation.spec.ts#L12
